# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Use custom format prompt
format = """\
[â”Œâ”€ ](238)$env_var\
 $all[â””â”€](238)$character"""

# Change the default prompt characters
[character]
# old config
success_symbol = "[â¯](238)"

# Shows an icon that should be included by zshrc script

[env_var.STARSHIP_DISTRO]
format = '[$env_value](white)'
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "white"
style_root = "white"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 1
truncation_symbol = "â€¦/"
home_symbol = "ğŸ  ~"
read_only_style = "197"
read_only = " ğŸ”’ "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "î‚  "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "â€¦/"
style = "green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "green"
conflicted = "ğŸš©"
up_to_date = "âœ… "
untracked = "ğŸš§ "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged = '[++\($count\)](green)'
renamed = "ğŸ”§ "
deleted = "ï€” "

[terraform]
format = "via [ğŸš€ terraform $version]($style) ï¥‚ [$workspace]($style) "
disabled = true

[kubernetes]
format = 'via [â›¯ $context\($namespace\)](bold purple) '
disabled = false

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
#detect_folders = []
#detect_extensions = ["yaml"]

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
